#!/bin/sh

# Run cargo machete
echo "Running cargo machete..."
cargo machete
if [ $? -ne 0 ]; then
  echo "cargo machete failed, aborting commit"
  exit 1
fi

# Run cargo test
echo "Running cargo test..."
cargo test --all --workspace --features mock_playback
if [ $? -ne 0 ]; then
  echo "cargo test failed, aborting commit"
  exit 1
fi

# If we made it here, everything passed and the push can proceed
echo "All tests passed, proceeding with push"
exit 0
