[files]
extend-exclude = ["mecomp-workspace-hack/*"]

[default.extend-words]
# don't correct the word "ratatui"" to "ratatouille"
ratatui = "ratatui"
# don't correct seeked to sought
seeked = "seeked"
# don't correct "leafs" to "leaves"
leafs = "leafs"
