[package]
name = "mecomp-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "This library is responsible for storing and retrieving data about a user's music library to and from an embedded surrealdb database."
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# shared dependencies
audiotags = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
readable = { workspace = true }
serde = { workspace = true }
surrealdb = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
tempfile = { workspace = true }


# other dependencies
metadata = { version = "0.1.8" }
