[package]
name = "mecomp-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "This library is responsible for storing and retrieving data about a user's music library to and from an embedded surrealdb database."
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# shared dependencies
anyhow = { workspace = true }
audiotags = { workspace = true }
clap = { workspace = true }
crossbeam = { workspace = true }
dirs = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
image = { workspace = true }
log = { workspace = true }
nutype = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
readable = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
toml_edit = { workspace = true }
thiserror = { workspace = true }
walkdir = { workspace = true }
tarpc = { workspace = true }

# server dependencies
surrealdb = { version = "1.1", features = ["kv-speedb"] }
