# This checks formatting, runs tests, and builds the project.

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "full"

concurrency:
  group: CI-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Run format separately.
  #
  # This will fast-cancel other CI early if this fails.
  #
  # `cargo fmt` checks _all_ code, regardless of the OS
  # or any `#[cfg]`'s, so this only needs to run on Linux.
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Format
        run: cargo fmt --check --all

  ci:
    runs-on: ubuntu-20.04 # latest version is missing some ALSA kernel modules
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends libasound2-dev pkg-config wget libavutil-dev libavformat-dev

      - name: set up dummy audio device
        run: |
          sudo apt install -y alsa-utils linux-modules-extra-$(uname -r)
          sudo modprobe snd-dummy
          sudo usermod -a -G audio $USER

      - name: Set up mold linker
        uses: rui314/setup-mold@v1

      - name: Install Rust toolchain
        run: |
          rustup show
          rustup -V
          rustup set profile minimal
          rustup toolchain install stable
          rustup override set stable

      - name: Initialize Cache
        uses: actions/cache@v4.0.2
        with:
          path: |
            ./target
            ~/.cargo
          key: ${{ runner.os }}-cargo-ci-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo test

      - name: Build
        run: cargo check --all-features
