# This catches typos.

name: Typo

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "full"

concurrency:
  group: Typo-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Spell Check
        uses: crate-ci/typos@master
